default_stages: [commit]
fail_fast: false
exclude: |
    (?x)(
      docs/yaml_search.json
    )

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-ast
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: mixed-line-ending

    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.9.0
      hooks:
          - id: pretty-format-toml
            args: [--autofix]

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.9-for-vscode
      hooks:
          - id: prettier
            args: [--print-width=88, --tab-width=4]
            exclude: |
                (?x)(
                  docs/cli.md|
                  PULL_REQUEST_TEMPLATE.md|
                  .github/semantic_release/release_notes.hbs
                )
            additional_dependencies:
                - prettier

    - repo: local
      hooks:
          - id: format
            name: format
            description: Runs Code Auto-Formatters
            entry: hatch run format
            language: system
            pass_filenames: false
          - id: lint
            name: lint
            description: Runs Code Linters
            entry: hatch run format
            language: system
            pass_filenames: false
            require_serial: false
