extends: default
rules:
    comments-indentation: disable
    document-start:       disable
    brackets:
        max-spaces-inside: 1
    braces:
        max-spaces-inside: 1
    colons:
        max-spaces-after: -1
    hyphens:
        max-spaces-after: 3
    indentation:
        indent-sequences: consistent
    line-length:
        level:                               warning
        allow-non-breakable-inline-mappings: true
        max:                                 120
    truthy:
        check-keys: false
ignore:  |
         tests/models/cassettes/
