name: Documentation Genrator

on:
  pull_request:
    branches:
      - main

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Github Workspace
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python Environment ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Test Dependencies
        run:  |
              python -m pip install --upgrade pip wheel
              python -m pip install tox
      - name: Tox Sphinx Genration
        run:  |
              cat README.md | grep -v readthedocs > docs/source/usage.md
              tox -e sphinx
      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message:        "Sphinx Documentation"
          add:            "docs"
