name: Documentation Generator

on:
      pull_request

jobs:
  make-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Github Workspace
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token:       ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Set up Python Environment ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Test Dependencies
        run:  |
              python -m pip install --upgrade pip wheel
              python -m pip install tox
      - name: Tox Sphinx Genration
        run:  |
              cat README.md | grep -v readthedocs > docs/source/usage.md
              tox -e sphinx
      - name: Commit Changes
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actor
          message:        Sphinx Documentation
          add:            docs
