name: Publish Release

on:
    release:
        types: [ published ]

jobs:
    publishing:
        runs-on: ubuntu-latest
        env:
            LOG_LEVEL:    DEBUG
            RIDB_API_KEY: ${{ secrets.RIDB_API_KEY }}
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Set up Python Environment 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Install Dependencies
                run:  |
                      python -m pip install --upgrade pip setuptools wheel build twine tox

            -   name: Set up Python Environment 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Run Tests
                run:  |
                      tox -e py39

            -   name: Build Python Package
                run:  |
                      python -m build

            -   name: Publish to PyPI
                run:  |
                      twine upload "${{ github.workspace }}/dist/*" \
                          --username ${{ secrets.PYPI_USERNAME }} \
                          --password ${{ secrets.PYPI_PASSWORD }}

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Declare Version Variable
                run:  |
                      VERSION=$(python setup.py --version)
                      echo CAMPLY_VERSION=${VERSION} >> $GITHUB_ENV

            -   name: Docker Image Building and Publishing
                id:   docker_build
                uses: docker/build-push-action@v2
                with:
                    push: True
                    tags: juftin/camply:latest,juftin/camply:${{ env.CAMPLY_VERSION }}
