name: Camply Pylint

on:
    push:
        branches: [ camply ]
    pull_request:
        branches: [ camply ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python 3.8
                uses: actions/setup-python@v1
                with:
                    python-version: 3.8
            -   name: Install dependencies
                run:  |
                      python -m pip install --upgrade pip
                      pip install pylint
                      pip install .  --use-feature=in-tree-build
            -   name: Analysing the code with pylint
                run:  |
                      python -m pylint ./camply `ls -R|grep .py$|xargs` --exit-zero