name: Tests

on:
    push:
        branches: [ camply ]
    pull_request:
        branches: [ camply ]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: [ 3.6, 3.7, 3.8, 3.9 ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python Environment ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install dependencies
                run:  |
                      python -m pip install --upgrade pip
                      python -m pip install flake8 pytest pylint
                      pip install .
            -   name: "Lint (flake8)"
                run:  |
                      # stop the build if there are Python syntax errors or undefined names
                      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                      # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            -   name: "Unit Tests (pytest)"
                run:  |
                      pytest tests/
            -   name: "Unit Tests (commandline)"
                run:  |
                      camply recreation-areas --search "Yosemite National Park"
                      camply campgrounds --rec-area-id 2991
                      camply campgrounds --search "Fire Tower Lookout" --state CA
                      camply campsites --rec-area-id 2991 --start-date 2021-09-15 --end-date 2021-09-16