name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Github Workspace
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version Fetcher
        run:  |
              echo PROJECT_NAME=$(python setup.py --name) >> ${GITHUB_ENV}
              echo PROJECT_VERSION=$(python setup.py --version) >> ${GITHUB_ENV}
      - name: Tag Setter
        run:  |
              echo PROJECT_TAG='v${{ env.PROJECT_VERSION }}' >> ${GITHUB_ENV}
              echo PROJECT_RELEASE='${{ env.PROJECT_NAME }} v${{ env.PROJECT_VERSION }}' >> ${GITHUB_ENV}
      - name: Draft a Release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          name:        ${{ env.PROJECT_RELEASE }}
          version:     ${{ env.PROJECT_VERSION }}
          tag:         ${{ env.PROJECT_TAG }}
          publish:     true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
