name: Release

on:
    push:
        branches:
        -   main

jobs:

    version-bump:
        name: version-bump
        runs-on: ubuntu-latest
        if: ${{ !startsWith( github.event.head_commit.message, 'Version Bump ðŸ¤–' ) }}
        steps:
        -   name: Check out the repository
            uses: actions/checkout@v3
            with:
                fetch-depth: 2
                ref: main
                token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        -   name: Fetch Related Pull Request Information
            uses: 8BitJonny/gh-get-current-pr@2.1.1
            id: PR
        -   name: Fetch Related Pull Request Labels
            run: |
                echo PR_LABELS='${{ steps.PR.outputs.pr_labels }}' >> ${GITHUB_ENV}
                echo "LABELS: ${{ steps.PR.outputs.pr_labels }}"
                echo "NUMBER: ${{ steps.PR.outputs.number }}"
                echo "URL: ${{ steps.PR.outputs.pr_url }}"
        -   name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.9'
        -   name: Upgrade pip
            run: |
                pip install --upgrade pip
                pip --version
        -   name: Install Poetry
            run: |
                pip install poetry
                poetry --version
        -   name: Version Bump - MAJOR
            if: contains(env.PR_LABELS, 'BUMP_MAJOR')
            run: |
                poetry version major
        -   name: Version Bump - MINOR
            if: contains(env.PR_LABELS, 'BUMP_MINOR')
            run: |
                poetry version minor
        -   name: Version Bump - PATCH
            if: contains(env.PR_LABELS, 'BUMP_PATCH')
            run: |
                poetry version patch
        -   name: Version Bump - DEFAULT PATCH
            if: |
                !contains(env.PR_LABELS, 'BUMP_MAJOR')
                  && !contains(env.PR_LABELS, 'BUMP_MINOR')
                  && !contains(env.PR_LABELS, 'BUMP_PATCH')
            run: |
                echo "Uh Oh, this doesn't look like it originated from a PR - or the PR was missing labels"
                echo "Proceeding with default version bump: PATCH"
                poetry version patch
        -   name: Update Version Variable
            run: |
                PROJECT_VERSION=$(poetry version --short)
                echo PROJECT_VERSION=${PROJECT_VERSION} >> $GITHUB_ENV
                REPLACED_VERSION_FILE_TEXT=$(grep -F -v "__version__" camply/_version.py)
                echo "${REPLACED_VERSION_FILE_TEXT}" > camply/_version.py
                echo "__version__ = \""${PROJECT_VERSION}\""" >> camply/_version.py
        -   uses: EndBug/add-and-commit@v9
            with:
                default_author: github_actions
                message: Version Bump ðŸ¤– ${{ env.PROJECT_VERSION }}

    github-release:
        name: github-release
        runs-on: ubuntu-latest
        needs: version-bump
        if: ${{ !startsWith( github.event.head_commit.message, 'Version Bump ðŸ¤–' ) }}
        steps:
        -   name: Check out the repository
            uses: actions/checkout@v3
            with:
                fetch-depth: 2
                ref: main
        -   name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.9'
        -   name: Upgrade pip
            run: |
                pip install --upgrade pip
                pip --version
        -   name: Install Poetry
            run: |
                pip install poetry
                poetry --version
        -   name: Declare Version Variable
            run: |
                PROJECT_VERSION=$(poetry version --short)
                PROJECT_NAME=$(poetry version | awk '{ print $1 }')
                echo PROJECT_VERSION=${PROJECT_VERSION} >> $GITHUB_ENV
                echo PROJECT_NAME=${PROJECT_NAME} >> $GITHUB_ENV
        -   name: Tag Setter
            run: |
                echo PROJECT_TAG='v${{ env.PROJECT_VERSION }}' >> ${GITHUB_ENV}
                echo PROJECT_RELEASE='${{ env.PROJECT_NAME }} v${{ env.PROJECT_VERSION }}' >> ${GITHUB_ENV}
        -   name: Draft a Release
            uses: release-drafter/release-drafter@v5
            with:
                config-name: release-drafter.yaml
                name: ${{ env.PROJECT_RELEASE }}
                version: ${{ env.PROJECT_VERSION }}
                tag: ${{ env.PROJECT_TAG }}
                publish: true
            env:
                GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
