name: Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches: [ "**" ]
    schedule:
        -   cron: "0 12 1 * *"
jobs:
    test-suite:
        runs-on: ubuntu-latest
        strategy:
            fail-fast:    true
            matrix:
                include:
                    - { name: 'Python 3.9', python: '3.9', tox: py39 }
                    - { name: 'Python 3.8', python: '3.8', tox: py38 }
                    - { name: 'Python 3.7', python: '3.7', tox: py37 }
                    - { name: 'Python 3.6', python: '3.6', tox: py36 }
            max-parallel: 1
        env:
            LOG_LEVEL:    DEBUG
            RIDB_API_KEY: ${{ secrets.RIDB_API_KEY }}
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Set up Python Environment ${{ matrix.python }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python }}
            -   name: Install Test Dependencies
                run:  |
                      python -m pip install --upgrade pip wheel
                      python -m pip install tox
            -   name: Tox Test Suite
                run:  |
                      echo "::add-matcher::.github/matchers/python.json"
                      tox -e ${{ matrix.tox }}
                      echo "::remove-matcher owner=python::"
